### PR TITLE
Fix PiCT reported bugs + build enhancements (10).

### PR DESCRIPTION
**Pull request by swoocn**
- Navbar alerts: Alert messages obscure the navbar (green navigation bar at top of all screens), replace by integrated alert
- Mac integration into Map of Pi navbar
- Seller reg screen, Retail Outlet placeholder fix
- Seller reg, screen default values fix
- Reviews screen: review photo display fix
- Reviews screen: fix review submission issue per @tate1650's analysis.
- Reviews screen: remove auto capabilities in search field.
- Added Arabic language translation
- Adjust error logging for frontend + backend for Sentry.io

**[see commits]**

_This PR is subject to change if additional bugs are resolved before approval._

### CODE REVIEW

**Comment by swoocn** [comment]
Hi @tate1650 - this PR is getting pretty lengthy; can you please review and approve when you can?  Thanks!

**Comment by swoocn** [comment]
Hi @tate1650 - This PR now includes the fix for review submission that you helped diagnose. Could you please ensure this update replaces the previous workaround you implemented? Let me know if you have any questions. Thanks! 👍

**Comment by swoocn** [comment]
Hi again @tate1650 - The team would like to maintain a change log or release notes to help publicize updates.  Could you please let me know once the changes have been deployed to production so we can share these updates accordingly?  Thanks again!

**Review by tate1650 — APPROVED** [review]
Done! Apologies for the delay.

> Could you please ensure this update replaces the previous workaround you implemented?

Sure thing, looks like your solution is pretty similar to (albeit more comprehensive than) mine, so it shouldn't be too difficult to adjust.

> Could you please let me know once the changes have been deployed to production so we can share these updates accordingly?

Yep, can do!

**Pull request merged**
