### PR TITLE
Fix PiCT reported bugs.

### PR DESCRIPTION
**Pull request by swoocn**
- Unable to reproduce the issue on my device, but attempted a few changes that may fix the issue for Bug Description - _Can't press on set sell center for half of the mods._ 🤞
If not, will need to revisit.
- Fixed _(PiCT) Seller Registration screen “Save” button does not respond unless a seller type is selected.
- **Set Search Center** and **Set Sell Center** resolved and functional.
- Introduce new Findme feature; WIP.
- Attempt to fix staging environment issue _(PiCT) Landing page search: Search stopped working_. 

**[see commits]**

_This PR is subject to change if additional bugs are resolved before approval._

### CODE REVIEW

**Comment by swoocn** [comment]
Please review new changes and approve accordingly @tate1650.
Thanks!

**Comment by tate1650** [comment]
> Introduce new Findme feature; WIP.
Is this WIP feature still a WIP? If so, is it in a state where it's safe to put it out onto staging without introducing more bugs?

**Review by tate1650 — APPROVED** [review]
These changes LGTM, although I'm waiting to merge until I get confirmation that the WIP findme feature is either 1) done or 2) in a safe state to deploy to staging.

**Comment by swoocn** [comment]
> > Introduce new Findme feature; WIP.
> 
> Is this WIP feature still a WIP? If so, is it in a state where it's safe to put it out onto staging without introducing more bugs?

Good question, @tate1650.  The WIP Findme feature is currently just an HTML dropdown element and hasn’t been completely integrated with any of our existing processes yet.  You may consider it purely a visual addition, as shown in the attached screenshot, and it shouldn't introduce any new bugs.

image

**Comment by tate1650** [comment]
Ah okay, that's fine. I thought that dropdown was already present, but as long as it shouldn't cause any issues then that's fine with me. :)

**Pull request merged**
